### ISSUE TITLE
Dataset is missing ! No such file or directory: 'stop.xlsx' 

### ISSUE THREAD

**Issue by rafikfartas** [Elmehdidebug/NLP-for-dialectDetection-TopicDetection-SentimentAnalysis#1]
Hello,
First, thank you for this project it's a huge ressource for us.
I downloaded all the modules nedded and when running "python model.py" its says (No such file or directory: 'stop.xlsx'), i guess the dataset is missing or i don't know if it's just a model and i should use my dataset instead, give us some informations ASAP please.
Thank you so much

```
C:\Users\ASUS\Desktop\M1 Info\PDL\NLP-for-arabic_dialect_Detection-TopicDetection-SentimentAnalysis-main>python model.py
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
Traceback (most recent call last):
  File "model.py", line 27, in <module>
    c = pd.read_excel('stop.xlsx')
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\io\excel\_base.py", line 364, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\io\excel\_base.py", line 1191, in __init__
    ext = inspect_excel_format(
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\io\excel\_base.py", line 1070, in inspect_excel_format
    with get_handle(
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\io\common.py", line 711, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'stop.xlsx'
```

**Comment by Elmehdidebug** [comment]
Hello,

Thank you for your email, yes you are right, I didn't upload that file and
also other files, I will do it as soon as possible.

Best regards.

**Comment by rafikfartas** [comment]
Okey, thank you so much.
